package ru.home.meet_bot.botapi;

public enum BotState {
    ASK_DESIRED,
    GET_DESCRIPTION,
    CHOOSE_DATE,
    CHOOSE_TIME,
    CHOOSE_PLACE,
    ADD_LINK,
    SHOW_CREATED_MEET,
    FILLING_MEET,
    ASK_CHANGE_MEET,
    SHOW_ALL_MEETS,
    SHOW_USER_MEETS,
    CHOOSE_ACT,
    ASK_NOTIFY,
    ASK_CAUSE,
    SEND_NOTIFY,
    GO_BACK,
    DELETE_MEET,
    SUBSCRIBE,
}
